package com.arifhasnat.bangladeshpoliceservice;

public class Word {

	public static String word[]={"Dhaka ঢাকা সদর", 
		 "Gazipur  গাজীপুর", 
		 "Faridpur  ফরিদপুর  ","Jamalpur জামালপুর", 
		 "GopalGanj গোপালগঞ্জ", 
		 "KishorGonj কিশোরগঞ্জ", 
		 "Madaripur মাদারীপুর ","ManikGong মানিকগঞ্জ", 
		 "NarayonGanj নরায়নগঞ্জ", 
		 "MunshiGanj মুন্সিগঞ্জ", 
		 "Mymensinj ময়মনসিংহ", 
		 "Narshindi নরসিংদী", 
		 "Rajbari রাজবাড়ী", 
		 "Shariyatput শরিয়তপুর", 
		 "Sherpur শেরপুর", 
		 "Tangail টাঙ্গাইল", 


		 "Chittagonj চট্টগ্রাম সদর", 
		 "BrawhmonBaria বাহ্মনবাড়িয়া "," Chadpur চাঁদপুর", 
		 "Laxmipur লক্ষীপুর", 
		 "Comilla কুমিল্লা", 
		"Cox's Bazar কক্সবাজার", 
		"Feni ফেনী", 
		"Noakhali নোয়াখালী", 
		 "BandarBan বান্দরবান", 
		 "Rangamati রাঙ্গামাটি", 
		"Khagrachori খাগড়াছড়ি", 
		 "Rajshahi রাজশাহী সদর ",
		 "Dinajpur দিনাজপুর ",
		 "Joypur Hat জয়পুরহাট", 
		 "Bagura বগুড়া ",
		 "Chapai Nawabgonj চাপাইনবাবগঞ্জ", 
		 "KuriGram কুড়িগ্রাম ",
		 "Lalmonirhat লালমনিরহাট", 
		 "Pabna পাবনা",
		 "Nilphamari নীলফামারী ",
		 "Gaibandha গায়বান্ধা ",
		 "Panchagor পঞ্চগড়  ","Naogoan নাওগাঁ ",
		 "Naotore নাটোর ",
		 "shiraGonjসিরাজগঞ্জ", 
		 " Rangpur রংপুর ",
		 "Thakurgaon ঠাকুরগাঁও ",
		 "Netrakona নেত্রকোনা ",
		 "Khulna খুলনা সদর", 
		"Bagerhat বাগেরহাট ","Chuyadanga চুয়াডাঙ্গা",
		 "Kustia কুষ্টিয়া ",
		 "Jessor যশোর ",
		 "Jhinadah ঝিনাইদহ ",
		 "Magura মাগুরা ",
		 "Meherpur মেহেরপুর ",
		 "Naraile নড়াইল ",
		 "Shatkhira সাতক্ষীরা ",


		 "Sylet সিলেট সদর ",
		 "MowloviBazar মৌলভীবাজার", 
		 "Habigown হবিগঞ্জ ",
		 "Sunamgown সুনামগঞ্জ ",
		 "Barishal বরিশাল সদর ",
		 "Barguna বরগুনা ",
		 "Bhola ভোলা ",
		"Jhalokhathi ঝালকাঠি ",
		 "Patuakhali পটুয়াখালী", 
		 "Ferojpur ফিরোজপুর" 
};
}
